### ISSUE TITLE
无法正确获取Kafka监控数据

### ISSUE THREAD

**Issue by labingIt** [xaecbd/KafkaCenter#142]
我点击Monitor > Producer，想获取写入速率等信息，无法正常获取，报错信息如下：
```
08:43:11,541 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
08:43:11,543 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
08:43:11,543 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/syk/KafkaCenter-master/KafkaCenter-Core/target/KafkaCenter-Core-2.3.0.jar!/BOOT-INF/classes!/logback.xml]
08:43:11,545 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
08:43:11,545 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/syk/KafkaCenter-master/KafkaCenter-Core/target/KafkaCenter-Core-2.3.0.jar!/BOOT-INF/lib/KafkaCenter-Base-2.3.0.jar!/logback.xml]
08:43:11,545 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/syk/KafkaCenter-master/KafkaCenter-Core/target/KafkaCenter-Core-2.3.0.jar!/BOOT-INF/classes!/logback.xml]
08:43:11,583 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@26f67b76 - URL [jar:file:/home/syk/KafkaCenter-master/KafkaCenter-Core/target/KafkaCenter-Core-2.3.0.jar!/BOOT-INF/classes!/logback.xml] is not of type file
08:43:11,669 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
08:43:11,671 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
08:43:11,683 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
08:43:11,690 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
08:43:11,754 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
08:43:11,760 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
08:43:11,787 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@356473385 - No compression will be used
08:43:11,788 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@356473385 - Will use the pattern logs/info.%d{yyyy-MM-dd}.log for the active file
08:43:11,793 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/info.%d{yyyy-MM-dd}.log'.
08:43:11,793 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
08:43:11,798 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Thu Dec 09 08:43:11 UTC 2021
08:43:11,799 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
08:43:11,800 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: logs/info.2021-12-09.log
08:43:11,800 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [null]
08:43:11,801 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
08:43:11,801 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ERROR_FILE]
08:43:11,801 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@2136344592 - No compression will be used
08:43:11,801 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@2136344592 - Will use the pattern logs/error.%d{yyyy-MM-dd}.log for the active file
08:43:11,802 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/error.%d{yyyy-MM-dd}.log'.
08:43:11,802 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
08:43:11,802 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Thu Dec 09 08:43:11 UTC 2021
08:43:11,802 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
08:43:11,805 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ERROR_FILE] - Active log file name: logs/error.2021-12-09.log
08:43:11,805 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ERROR_FILE] - File property is set to [null]
08:43:11,805 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.nesc.ec.bigdata] to INFO
08:43:11,805 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache] to ERROR
08:43:11,805 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.I0Itec.zkclient] to ERROR
08:43:11,805 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
08:43:11,805 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
08:43:11,806 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
08:43:11,806 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ERROR_FILE] to Logger[ROOT]
08:43:11,806 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
08:43:11,807 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@69d9c55 - Registering current configuration as safe fallback point

 _  __      __ _            _____           _
| |/ /     / _| |          / ____|         | |
| ' / __ _| |_| | ____ _  | |     ___ _ __ | |_ ___ _ __
|  < / _` |  _| |/ / _` | | |    / _ \ '_ \| __/ _ \ '__|
| . \ (_| | | |   < (_| | | |___|  __/ | | | ||  __/ |
|_|\_\__,_|_| |_|\_\__,_|  \_____\___|_| |_|\__\___|_|


2021-12-09 08:43:12,240 INFO  [main] Application: Starting Application v2.3.0 on newmem2 with PID 3994597 (/home/syk/KafkaCenter-master/KafkaCenter-Core/target/KafkaCenter-Core-2.3.0.jar started by root in /home/syk/KafkaCenter-master/KafkaCenter-Core/target)
2021-12-09 08:43:12,244 INFO  [main] Application: No active profile set, falling back to default profiles: default
2021-12-09 08:43:13,936 INFO  [main] TomcatWebServer: Tomcat initialized with port(s): 8100 (http)
2021-12-09 08:43:13,986 INFO  [main] ContextLoader: Root WebApplicationContext: initialization completed in 1700 ms
2021-12-09 08:43:14,322 WARN  [main] HikariConfig: KafkaCenterHikariCP - idleTimeout is close to or more than maxLifetime, disabling it.
2021-12-09 08:43:14,324 INFO  [main] HikariDataSource: KafkaCenterHikariCP - Starting...
2021-12-09 08:43:14,530 INFO  [main] HikariDataSource: KafkaCenterHikariCP - Start completed.
2021-12-09 08:43:15,844 INFO  [main] ThreadPoolTaskExecutor: Initializing ExecutorService 'applicationTaskExecutor'
2021-12-09 08:43:15,937 INFO  [main] WelcomePageHandlerMapping: Adding welcome page: class path resource [static/index.html]
2021-12-09 08:43:16,213 INFO  [main] DefaultSecurityFilterChain: Creating filter chain: Ant [pattern='/**'], [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@61e7bf2f, org.springframework.security.web.context.SecurityContextPersistenceFilter@6e1b9411, org.springframework.security.web.header.HeaderWriterFilter@3659d7b1, org.springframework.security.web.authentication.logout.LogoutFilter@470a659f, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@5ec46cdd, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@4016ccc1, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@1a28b346, org.springframework.security.web.session.SessionManagementFilter@73a19967, org.springframework.security.web.access.ExceptionTranslationFilter@6b2e0f78, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@42d73c61]
2021-12-09 08:43:16,243 INFO  [main] EndpointLinksResolver: Exposing 2 endpoint(s) beneath base path '/actuator'
2021-12-09 08:43:16,301 INFO  [main] TomcatWebServer: Tomcat started on port(s): 8100 (http) with context path ''
2021-12-09 08:43:16,304 INFO  [main] Application: Started Application in 4.421 seconds (JVM running for 5.111)
2021-12-09 08:43:32,735 INFO  [http-nio-8100-exec-1] DispatcherServlet: Initializing Servlet 'dispatcherServlet'
2021-12-09 08:43:32,755 INFO  [http-nio-8100-exec-1] DispatcherServlet: Completed initialization in 14 ms
2021-12-09 08:43:36,408 WARN  [http-nio-8100-exec-8] RestClient: request [POST http://localhost:9200/kafka_center_monitor*/_search] returned 1 warnings: [299 Elasticsearch-7.16.0-6fc81662312141fe7691d7c1c91b8658ac17aa0d "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.16/security-minimal-setup.html to enable security."]
2021-12-09 08:43:36,409 WARN  [http-nio-8100-exec-10] RestClient: request [POST http://localhost:9200/kafka_center_monitor*/_search] returned 1 warnings: [299 Elasticsearch-7.16.0-6fc81662312141fe7691d7c1c91b8658ac17aa0d "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.16/security-minimal-setup.html to enable security."]
2021-12-09 08:43:56,067 WARN  [http-nio-8100-exec-7] RestClient: request [POST http://localhost:9200/kafka_center_monitor*/_search] returned 1 warnings: [299 Elasticsearch-7.16.0-6fc81662312141fe7691d7c1c91b8658ac17aa0d "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.16/security-minimal-setup.html to enable security."]
2021-12-09 08:43:56,080 ERROR [http-nio-8100-exec-1] MonitorService: getBrokerMetric has error
java.lang.NullPointerException: null
        at org.nesc.ec.bigdata.service.MonitorService.getReplicaBroker(MonitorService.java:507)
        at org.nesc.ec.bigdata.service.MonitorService.getBrokerMetric(MonitorService.java:491)
        at org.nesc.ec.bigdata.controller.MonitorController.topicMetric(MonitorController.java:187)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by labingIt** [comment]
ES版本7.16，Kafka版本2.8.1，无Kafka Connect，application.properties如下：
```
# ----------------------------------------------
# MAIN APPLICATION CONFIG

# url and port where application is published
server.port=8100
public.url=http://(隐藏):8100

# enable/disable debug logging level
debug=false

# session timeout in seconds (21600 = 6 hours)
server.servlet.session.timeout=21600

# admin user/password to manage KafkaCenter
spring.security.user.name=admin
spring.security.user.password=admin

# url and user/password for mysql database
# if remote, make sure the user has adequate privileges (google "mysql grant privileges")
spring.datasource.url=jdbc:mysql://localhost:3306/kafka_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
spring.datasource.username=kafkacenter
spring.datasource.password=passwd


# ----------------------------------------------
# MONITOR

# enable/disable functionality
monitor.enable=true

# statistic collection frequency
monitor.collect.period.minutes=1

# elasticsearch config
monitor.elasticsearch.hosts=localhost:9200
monitor.elasticsearch.index=kafka_center_monitor
#monitor.elasticsearch.auth.user=
#monitor.elasticsearch.auth.password=


# ----------------------------------------------
# ALERTS

# enable/disable functionality to send consumer group lag alerts
alert.enable=false

# url of alert service (leave empty for regular internal application)
alert.service=

# default time window and threshold 
alert.dispause=2

# default threshold
alert.threshold=1000

# environment variable included in alerts
alter.env=other


# ----------------------------------------------
# EMAILS

# enable/disable functionality to trigger emails for alerts
mail.enable=false

# configuration of external mail host
spring.mail.host=
spring.mail.username=KafkaCenter@xaecbd.com
#spring.mail.password=xxxix


# ----------------------------------------------
# KAFKA CONNECT

# url where kafka connect is installed
connect.url=http://localhost:8000/#/


# ----------------------------------------------
# OAUTH2 KAFKACENTER LOGIN

# enable/disable functionality to log into application via external oauth service
generic.enabled=false

# name of service on login page
generic.name=oauth2 Login

# settings of external oauth service
generic.auth_url=
generic.token_url=
generic.redirect_utl=
generic.api_url=
generic.client_id=
generic.client_secret=
generic.scopes=


# ----------------------------------------------
# VARIOUS ADVANCED CONFIGS

# default kafka topic retention time
system.topic.ttl.h=1

# enable/disable default spring boot actuator health indicators
management.health.defaults.enabled=false

# hikari connection pool configurations 
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.pool-name=KafkaCenterHikariCP
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-test-query=SELECT 1

# mysql driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# enable/disable collecting list of kafka topics regularly, and set interval of collection
collect.topic.enable=true
collect.topic.period.minutes=10

# enable/disable that collection threads only collect metrics of certain cluster locations
# the location specified must be one of remote.locations below
monitor.collector.include.enable=false
monitor.collector.include.location=dev

# enable remote querying to improve lag collection behaviour, solving problems induced by latency between different locations
remote.query.enable=false
remote.hosts=gqc@localhost2:8080
remote.locations=dev,gqc

# enable/disable collecting list of ksql job regularly, and set interval of collection
collect.ksql.info.job.enable=false
collect.ksql.info.job.period.minutes=5

# enable/disable collecting list of connector job regularly, and set interval of collection
collect.connector.job.enable=false
collect.connector.job.period.minutes=4

# alert group api for alert
alert.alarm.group.api=
```

**Comment by TrumanDu** [comment]
@labingIt broker是否开启jmx端口？
