### ISSUE TITLE
项目运行起来了，但是 jdk1.8 混搭 jdk11 总会出各种问题

### ISSUE THREAD

**Issue by geekyouth** [xaecbd/KafkaCenter#4]
启动时的疑惑：
主配置文件里面的 connect.url=http://localhost:8000/#/ ，我在项目里面全局搜索只发现两个地方用到该参数，docker 启动时。然后我找到了 KafkaConnectUi 官网，我猜想这个模块不是必须的吧，所以就没管它。

运行环境：
centos7 + ES7.4 + 默认全局JDK1.8 + mysql-5.7.26(win10)
KafkaCenter-2.0.0 使用 jdk11 启动（/opt/module/jdk-11.0.5/bin/java -jar KafkaCenter-2.0.0.jar）

修改的配置：
spring.datasource.url=jdbc:mysql://lx:3306/kafka_center?useUnicode=true&characterEncoding=utf-8
monitor.elasticsearch.hosts=cdh231:9200,cdh232:9200,cdh233:9200

es 状态正常：
![image](https://user-images.githubusercontent.com/12899262/77841639-16e63080-71c2-11ea-94b2-ae1375cf8dbb.png)
![image](https://user-images.githubusercontent.com/12899262/77841674-18aff400-71c2-11ea-845c-66723e57902b.png)

然后打开网页 http://cdh231:8080：
添加了kafka 集群，生产和消费功能正常，但是所有的图表监控都看不到曲线。
![image](https://user-images.githubusercontent.com/12899262/77842338-798bfc00-71c3-11ea-9edb-98e1c2f1f788.png)
![image](https://user-images.githubusercontent.com/12899262/77842347-93c5da00-71c3-11ea-9919-1e041b974e7e.png)
![image](https://user-images.githubusercontent.com/12899262/77842396-30887780-71c4-11ea-8231-e95217f5ee42.png)
![image](https://user-images.githubusercontent.com/12899262/77842335-68db8600-71c3-11ea-9d9a-e892de45ef93.png)

报错日志：
2020-03-29 13:27:45,438 ERROR [pool-2-thread-2] CollectMetricsJob: monitor metric  error.
java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: cdh232; nested exception is:
        java.net.ConnectException: 拒绝连接 (Connection refused)]
        at java.management.rmi/javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:370)
        at java.management/javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
        at org.nesc.ec.bigdata.common.util.JmxCollector.connect(JmxCollector.java:51)
        at org.nesc.ec.bigdata.common.util.JmxCollector.getJmxConnector(JmxCollector.java:37)
        at org.nesc.ec.bigdata.common.util.JmxCollector.metricEveryBrokerTopic(JmxCollector.java:65)
        at org.nesc.ec.bigdata.common.util.JmxCollector.metricEveryBroker(JmxCollector.java:54)
        at org.nesc.ec.bigdata.service.HomeService.brokerMetric(HomeService.java:127)
        at org.nesc.ec.bigdata.job.CollectMetricsJob.collectMetric(CollectMetricsJob.java:53)
        at org.nesc.ec.bigdata.job.CollectorAndAlertJob.lambda$runCollectMetricsJob$1(CollectorAndAlertJob.java:91)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.naming.ServiceUnavailableException: null
        at jdk.naming.rmi/com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:137)
        at java.naming/com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:207)
        at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
        at java.management.rmi/javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1839)
        at java.management.rmi/javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1813)
        at java.management.rmi/javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:302)
        ... 14 common frames omitted
Caused by: java.rmi.ConnectException: Connection refused to host: cdh232; nested exception is:
        java.net.ConnectException: 拒绝连接 (Connection refused)
        at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
        at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:209)
        at java.rmi/sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:196)
        at java.rmi/sun.rmi.server.UnicastRef.newCall(UnicastRef.java:338)
        at java.rmi/sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:116)
        at jdk.naming.rmi/com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:133)
        ... 19 common frames omitted
Caused by: java.net.ConnectException: 拒绝连接 (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.base/java.net.Socket.connect(Socket.java:608)
        at java.base/java.net.Socket.connect(Socket.java:557)
        at java.base/java.net.Socket.<init>(Socket.java:453)
        at java.base/java.net.Socket.<init>(Socket.java:230)
        at java.rmi/sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40)
        at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
        ... 24 common frames omitted

补充说明：
我的 cdh6.2 集群部署了es7.0，java环境全是1.8，但是 KafkaCenter-2.0.0  这个项目要求使用jdk11，然后我就使用jdk11 启动该项目，但是宿主机全局的环境变量是jdk1.8，上面部署了es 集群，使用过程，发现es服务无法连接，我猜想是否因为jdk不一致导致？

疑问：
1-是否有计划兼容jdk1.8？
2-kafka 消费进度的曲线怎么展示出来？以及兼容版本列表？
3-es 服务提示拒绝连接是不是jdk不兼容？应该升级全局jdk 到11吗？
4-KafkaConnectUi 模块有什么特殊作用吗？这是可选的吗？

**Comment by Dr-kyle** [comment]
1. connect 如果没用到，可以忽略掉该配置
2. 确保kafka jmx端口开启，因为集群一些数据是通过jmx端口获取的
3. 不兼容jdk8

**Comment by TrumanDu** [comment]
1.这块需要jdk11是因为ksql功能需要使用，排除该功能，是可以支持jdk1.8的，目前没有兼容jdk1.8的计划。如果你需要支持jdk1.8，可以提issue，需要这个需求的人多了我们可以考虑该提案！

**Comment by zhisheng17** [comment]
@TrumanDu hello，JDK 1.8 需求还是很大的，目前公司没有升级到 1.11 这么新的版本

**Comment by imperio-wxm** [comment]
JDK 1.8 需求+1

**Comment by TrumanDu** [comment]
@zhisheng17，可以重新提个issue，我这边拉一个jdk1.8分支。不过需要自己编译打包了！

**Comment by TrumanDu** [comment]
@zhisheng17 @imperio-wxm 已经列入计划 ! [support jdk 1.8](https://github.com/xaecbd/KafkaCenter/issues/13)

**Comment by TrumanDu** [comment]
@imperio-wxm @geekyouth @zhisheng17 目前已经支持jdk1.8
