### ISSUE TITLE
ElasticsearchService: queryDateIntervalOffset faild!

### ISSUE THREAD

**Issue by mulihong** [xaecbd/KafkaCenter#41]
Monitor ConsumerLag  is not data...
Monitor Lag The page cannot be load

env: elasticsearch 7.4.2   Authentication is not enabled

application.properties configure
monitor.enable=true
monitor.collect.period.minutes=5
monitor.elasticsearch.hosts=10.x.x.x:9200
monitor.elasticsearch.index=kafka_center_monitor
#是否启用收集线程指定集群收集
monitor.collector.include.enable=true
#收集线程指定location，必须属于remote.locations之中
monitor.collector.include.location=E4
collect.topic.enable=true
collect.topic.period.minutes=10
remote.query.enable=false
remote.hosts=gqc@localhost2:8080
remote.locations=dev,gqc,prd

kafkacenter.log 
2020-05-08 23:59:52,499 ERROR [http-nio-8080-exec-1] ElasticsearchService: queryDateIntervalOffset faild!
java.lang.NullPointerException: null
        at org.nesc.ec.bigdata.service.ElasticsearchService.parseDateIntervalResponse(ElasticsearchService.java:110)
        at org.nesc.ec.bigdata.service.ElasticsearchService.queryDateIntervalOffset(ElasticsearchService.java:94)
        at org.nesc.ec.bigdata.controller.MonitorController.getOffsetStatsInterval(MonitorController.java:223)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

**Comment by mulihong** [comment]
env:   elasticsearch 7.4.2   not auth

**Comment by Loernl** [comment]
your remote locations is dev,gqc,prd,But the location gathered by the cluster is not one of the remote locations you configured。eg:
remote.locations=dev,gqc,prd
monitor.collector.include.location=gqc

**Comment by TrumanDu** [comment]
@mulihong If you have any questions, let me know.
